fix gendoc
gendoc throws: `AttributeError: 'Sphinx' object has no attribute 'info'`

use logging provided by sphinx.util (not sure why it's using sphinx logger
but meh)

(cherry picked from commit 84819f67923d1648452fb5bc869430cb07159e11)

also, dropping migration tests from pre4.2 because no ones got time
for it.